
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-left*/left^!rightROLLrightUMINUSCOMPARISON LPAREN NUMBER ROLL RPARENexpr : NUMBERexpr : 'c' expr : expr '+' expr\n\t\t\t| expr '-' expr\n\t\t\t| expr '*' expr\n\t\t\t| expr '/' expr\n\t\t\t| expr '^' exprexpr : expr ROLL exprexpr : ROLL exprexpr : expr COMPARISON exprexpr : LPAREN expr RPARENexpr : expr '!' expr : '-' expr %prec UMINUS"
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,8,9,10,11,12,13,],[2,2,2,2,2,2,2,2,2,2,2,]),'c':([0,4,5,6,7,8,9,10,11,12,13,],[3,3,3,3,3,3,3,3,3,3,3,]),'ROLL':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[5,12,-1,-2,5,5,5,5,5,5,5,5,5,5,-12,-13,12,12,12,12,12,12,12,12,12,-11,]),'LPAREN':([0,4,5,6,7,8,9,10,11,12,13,],[6,6,6,6,6,6,6,6,6,6,6,]),'-':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[4,8,-1,-2,4,4,4,4,4,4,4,4,4,4,-12,-13,-9,8,-3,-4,-5,-6,-7,-8,8,-11,]),'$end':([1,2,3,14,15,16,18,19,20,21,22,23,24,25,],[0,-1,-2,-12,-13,-9,-3,-4,-5,-6,-7,-8,-10,-11,]),'+':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[7,-1,-2,-12,-13,-9,7,-3,-4,-5,-6,-7,-8,7,-11,]),'*':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[9,-1,-2,-12,-13,-9,9,9,9,-5,-6,-7,-8,9,-11,]),'/':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[10,-1,-2,-12,-13,-9,10,10,10,-5,-6,-7,-8,10,-11,]),'^':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[11,-1,-2,-12,-13,-9,11,11,11,11,11,-7,-8,11,-11,]),'COMPARISON':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[13,-1,-2,-12,-13,-9,13,-3,-4,-5,-6,-7,-8,13,-11,]),'!':([1,2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[14,-1,-2,-12,-13,-9,14,14,14,14,14,-7,-8,14,-11,]),'RPAREN':([2,3,14,15,16,17,18,19,20,21,22,23,24,25,],[-1,-2,-12,-13,-9,25,-3,-4,-5,-6,-7,-8,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,5,6,7,8,9,10,11,12,13,],[1,15,16,17,18,19,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> NUMBER','expr',1,'p_expr','diceparser.py',109),
  ('expr -> c','expr',1,'p_expr_c','diceparser.py',113),
  ('expr -> expr + expr','expr',3,'p_expr_arithmetic','diceparser.py',117),
  ('expr -> expr - expr','expr',3,'p_expr_arithmetic','diceparser.py',118),
  ('expr -> expr * expr','expr',3,'p_expr_arithmetic','diceparser.py',119),
  ('expr -> expr / expr','expr',3,'p_expr_arithmetic','diceparser.py',120),
  ('expr -> expr ^ expr','expr',3,'p_expr_arithmetic','diceparser.py',121),
  ('expr -> expr ROLL expr','expr',3,'p_expr_dice','diceparser.py',134),
  ('expr -> ROLL expr','expr',2,'p_expr_onedie','diceparser.py',144),
  ('expr -> expr COMPARISON expr','expr',3,'p_expr_comparison','diceparser.py',150),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','diceparser.py',162),
  ('expr -> expr !','expr',2,'p_expr_fact','diceparser.py',166),
  ('expr -> - expr','expr',2,'p_expr_minus','diceparser.py',170),
]
